/data/logs/frontend/*.log {
    daily
    rotate 30
    size 100M
    missingok
    notifempty
    compress
    delaycompress
    dateext
    postrotate
        nginx -s reopen 2>/dev/null || true
    endscript
}
